### ISSUE TITLE
Cannot identify trash folder, if in account settings the action for "when I delete a message" is not set to "Move to this folder .. "

### ISSUE THREAD

**Issue by zoe-translates** [Roy-Orbison/GTrash#2]
https://github.com/Roy-Orbison/GTrash/blob/e9be83b79a4e28c1b3bb767e5e56e7269fad52c1/background.js#L97-L112

This block of code tries to find the destination of the move by looking at which folder has the `type` property set to `"trash"`.

To my surprise, it seems that in Thunderbird (tested on 102.10.1), the outcome of this search depends on the user setting of "When I delete a message" for the account.

If "When I delete a message" is set to "Just mark it as deleted" or "Remove it immediately", none of the folders have `.type === "trash"`. The so-named "Trash" or "Deleted" folders actually won't have a `type` property at all; they're "just" plain folders. Consequently, the move will not happen.

Only by setting the "When I delete.." action as "Move it to this folder ..." can a `.type === "trash"` folder be identified. In this case, the action is no different from the "Delete" action.

This kinda defeats the purpose of the extension, which is

> to move selected messages to the Trash folder regardless of the mail account's _When I delete a message_ setting.

I wonder if this is a new issue caused by Thunderbird API breaking compatibility? If the `type` property can only be set to `"trash"` this way, by tying the property with the underlying action of deletion, it seems we have to fall back to something else, e.g. user preference?

**Comment by Roy-Orbison** [comment]
Does your Trash folder show the normal icon beside its label?

I'll look into this but in the meantime, so you can have the correct _When I delete a message_ setting, try the [FolderFlags add-on](https://addons.thunderbird.net/thunderbird/addon/folderflags/). It should let you verify (and set) the folder type.

**Comment by zoe-translates** [comment]
> Does your Trash folder show the normal icon beside its label?

If I set the delete action to "Just mark as deleted" or "Immediately remove it", it shows up just like any other ordinary folder -- default icon (not the "bin"), no "empty deleted" option in context menu. The name also becomes "Trash", no matter the original "display name" was (e.g. "Deleted" or something similar, probably depending on locale or server).

I don't know if this is the intended behaviour in TB. Honestly I don't remember if it has been like this before.

Thank you for the suggestion about the FolderFlags addon! It did restore the semantics of the folder once I manually set the folder's type to "Deleted". After that, your extension worked flawlessly.

Shall we close this issue?

**Comment by Roy-Orbison** [comment]
Leave it open for now, I'll check with a fresh profile, thanks.

I have personally experienced the same issue in the past, where a special IMAP folder is not correctly detected, and that flags add-on has fixed the issue for me. I seem to remember it usually being the *Drafts* folder.

**Comment by Roy-Orbison** [comment]
I just spun up a fresh profile, added a gmail account and the trash folder had the correct icon. I set only the delete option to "just mark" before installing this add-on, nothing else. Using its default shortcut correctly trashed a message.

Thanks for reporting, though, now others can see how to fix broken IMAP flags.
